/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AnonAadhaarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "storedPublicKeyHash"
      | "verifier"
      | "verifyAnonAadhaarProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "storedPublicKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyAnonAadhaarProof",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      BigNumberish[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "storedPublicKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAnonAadhaarProof",
    data: BytesLike
  ): Result;
}

export interface AnonAadhaar extends BaseContract {
  connect(runner?: ContractRunner | null): AnonAadhaar;
  waitForDeployment(): Promise<this>;

  interface: AnonAadhaarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  storedPublicKeyHash: TypedContractMethod<[], [bigint], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  verifyAnonAadhaarProof: TypedContractMethod<
    [
      nullifierSeed: BigNumberish,
      nullifier: BigNumberish,
      timestamp: BigNumberish,
      signal: BigNumberish,
      revealArray: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      groth16Proof: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "storedPublicKeyHash"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAnonAadhaarProof"
  ): TypedContractMethod<
    [
      nullifierSeed: BigNumberish,
      nullifier: BigNumberish,
      timestamp: BigNumberish,
      signal: BigNumberish,
      revealArray: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      groth16Proof: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
