/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAnonAadhaar,
  IAnonAadhaarInterface,
} from "../../../../@anon-aadhaar/contracts/interfaces/IAnonAadhaar";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nullifierSeed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nullifier",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "signal",
        type: "uint256",
      },
      {
        internalType: "uint256[4]",
        name: "revealArray",
        type: "uint256[4]",
      },
      {
        internalType: "uint256[8]",
        name: "groth16Proof",
        type: "uint256[8]",
      },
    ],
    name: "verifyAnonAadhaarProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAnonAadhaar__factory {
  static readonly abi = _abi;
  static createInterface(): IAnonAadhaarInterface {
    return new Interface(_abi) as IAnonAadhaarInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAnonAadhaar {
    return new Contract(address, _abi, runner) as unknown as IAnonAadhaar;
  }
}
