/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAnonAadhaarGroth16Verifier,
  IAnonAadhaarGroth16VerifierInterface,
} from "../../../../@anon-aadhaar/contracts/interfaces/IAnonAadhaarGroth16Verifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "_pA",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "_pB",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "_pC",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[9]",
        name: "publicInputs",
        type: "uint256[9]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAnonAadhaarGroth16Verifier__factory {
  static readonly abi = _abi;
  static createInterface(): IAnonAadhaarGroth16VerifierInterface {
    return new Interface(_abi) as IAnonAadhaarGroth16VerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAnonAadhaarGroth16Verifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAnonAadhaarGroth16Verifier;
  }
}
