/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAnonAadhaar } from "./IAnonAadhaar";
export type { IAnonAadhaarGroth16Verifier } from "./IAnonAadhaarGroth16Verifier";
