/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IAnonAadhaar",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAnonAadhaar__factory>;
    getContractFactory(
      name: "IAnonAadhaarGroth16Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAnonAadhaarGroth16Verifier__factory>;
    getContractFactory(
      name: "AnonAadhaar",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AnonAadhaar__factory>;
    getContractFactory(
      name: "DIDRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DIDRegistry__factory>;

    getContractAt(
      name: "IAnonAadhaar",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAnonAadhaar>;
    getContractAt(
      name: "IAnonAadhaarGroth16Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAnonAadhaarGroth16Verifier>;
    getContractAt(
      name: "AnonAadhaar",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AnonAadhaar>;
    getContractAt(
      name: "DIDRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DIDRegistry>;

    deployContract(
      name: "IAnonAadhaar",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAnonAadhaar>;
    deployContract(
      name: "IAnonAadhaarGroth16Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAnonAadhaarGroth16Verifier>;
    deployContract(
      name: "AnonAadhaar",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AnonAadhaar>;
    deployContract(
      name: "DIDRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DIDRegistry>;

    deployContract(
      name: "IAnonAadhaar",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAnonAadhaar>;
    deployContract(
      name: "IAnonAadhaarGroth16Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAnonAadhaarGroth16Verifier>;
    deployContract(
      name: "AnonAadhaar",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AnonAadhaar>;
    deployContract(
      name: "DIDRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DIDRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
